redpanda-data/openmessaging-benchmark

benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java
benchmark-framework/src/main/java/io/openmessaging/benchmark/TestResult.java
bin/generate_charts.py

Includes the following fields.
* An optional version of the service passed along by the user with --service-version. This is a plain string and can be anything like an actual version/commit etc. This is embedded in the result.json
* beginTime (beginning time of the workload)
* endTime (end time of the workload)
The goal is to include as much metadata as we can in the result.json so that we need not look elsewhere to figure out when it was run or what it was run against.

Annotate additional metadata in the result file

---

bin/generate_charts.py

Fixes include:
1. Allow workloads with a "/" in the name (as some do have this in the upstream repo).
2. Restore capability for index.html to have an h2 section per workload. 
3. Embed SVG files into html file to allow for easier distribution.
4. Add --coalesce-workloads flag to allow for all workloads to be rendered on the same set of charts
5. Update to use new RedPanda colours in graphs
6. Make the duplicate files error condition a warning and log to stderr.

Fixes to Generate Charts

---

driver-redpanda/deploy/deploy.yaml

chrony.conf was being written to the wrong direction. Added in config to monitor NTP through Prometheus and an NTP dashboard in Grafana.

Fix to ensure that chrony.conf is in the right location

---

driver-redpanda/README.md

This adds basic instructions for using `generate_charts.py` to the README.

Add instructions on generating charts

---

driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkDriver.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/RedpandaBenchmarkDriver.java

Fix to prevent deployments with multiple workers failing to delete topics because they all try to delete-all at the same time.

Topic deletion fix

---

driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkConsumer.java

Changes to move the offset commit behaviour back closer to the default behaviour, but also to avoid flooding the Kafka client with async commits. At the very least this will only submit async requests once the previous async request has come back.
New behaviour:
We're only going to submit an async commit request if:
- autoCommit is disabled AND
- there are offsets to commit AND
- offsetCommitLingerMs is zero (the default, so no waiting for async callbacks at all) OR
- we've waited lingerMs milliseconds since the last callback completed (+ve or -ve)

Coalesce async offset commits

---

driver-redpanda/deploy/terraform.tfvars

The old AMI has problems with TLS certs that cause problems downloading certificates from the Grafana repo

Update Ubuntu AMI

---

driver-nats-streaming/pom.xml

CI failed to build omb with the following error:
```
[ERROR] Failed to execute goal on project driver-nats-streaming: Could not resolve dependencies for project io.openmessaging.benchmark:driver-nats-streaming:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at io.nats:java-nats-streaming:jar:2.1.0 -> com.google.protobuf:protobuf-java:jar:3.22.0-RC1: Failed to read artifact descriptor for com.google.protobuf:protobuf-java:jar:3.22.0-RC1: Could not find artifact com.google.protobuf:protobuf-parent:pom:3.22.0-RC1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```
This PR:
* updates the version of java-nats-streaming: `2.1.0` -> `2.2.0`: according to  https://github.com/nats-io/stan.java/releases/tag/2.2.0 updates the protobuf version
* adds explicit dependency for `guava`: …

fix omb build failure

---

bin/benchmark

Fix to enable the benchmark script to be called from any location rather than just the install directory (also allows non-root running)

Fix to enable the benchmark script to be called from any location

---

.gitignore
benchmark-framework/src/main/java/io/openmessaging/benchmark/Workload.java
benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/TopicsInfo.java

This patch set allows for having different topics that are produced and consumed too.
The main motivation for this is to run OMB against a Wasm powered Data Transform and see the E2E latency.
This comes with an example transform that converts json into avro:
OMB should produce into a topic called `json` using the payload in `payload/payload-1Kb.json`. The deployed data transform will take that json and convert it to avro and write to the `avro` topic, which OMB will consume from.
Commits:
- Add .vim to gitignore
- Add the ability to specify existing topics for produce or consume
- Add an example json -> avro data transform
- Add an example json payload for the wasm transform

Wasm Data Transform support for OMB

---

benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/WorkerHandler.java
benchmark-framework/src/test/java/io/openmessaging/benchmark/worker/TestWorkerHandler.java

When we serialize a histogram to a byte array, the intermediate
ByteBuffer that we pass may be too small which may result in silent
truncation of the encoded histogram.
This will manifest on the driver side as a decoding failure.
This change detects this case and grows the buffer by a
factor of 2 until it fits.
Fixes https://github.com/openmessaging/benchmark/issues/369.

Grow buffer if histogram doesn't fit

---

benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java

Remove the histogram retry logic as we've fixed the underyling bug and it's no longer necessary (and is actively harmful).

Remove retries in printAndCollectStats

---

benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/PeriodStats.java

Currently many of the histograms use the HDR Recorder constructor which sets the highest trackable value to 60 seconds, so as soon as latencies exceed that value we will get ArrayOutOfBoundsException inside the HDR histogram class.
Prevent this by using the auto-scaling version of the HDR histogram which will grow as needed to handle the observed values.

Use auto-adjusting histograms

---

bin/create_charts.py

If create_charts is passed only one set of results, additionally include a chart which shows all the various percentiles (p50, p75, ...) on one charts which is often more useful than several independent charts.
We do this only for single results because with multiple results we are already adding several series to the same chart: one for each series.

Add an "all percentiles view" to create_charts.py

---

deployment/README.md
deployment/pom.xml
pom.xml

Wires in a Maven plugin for building the Helm chart into a tarball. Currently requires having a local install of `helm` as it's not clear if the plugin supports non-x86/amd64 systems when it comes to auto-downloading Helm binaries. (It wasn't working on my linux/arm64 host.)

Convert the deployment directory into a Maven module.

---

bin/benchmark
bin/benchmark-worker

This is a trick I've used in other Java apps that are expected to utilize all the heap they're provided. It adds a small delay to startup, but should fault in virtual memory to back the JVM heap. This removes the chance of fatal OOM events when the JVM needs to grow the heap or cause a page fault at runtime.

Prevent runtime OOMs by having driver and worker JVMs pre-touch heap memory

---

driver-redpanda/deploy/deploy.yaml
driver-redpanda/deploy/requirements.yaml

allows working in cloud environments where there are no redpanda nodes

Update to use published grafana dashboards

---

bin/benchmark
bin/benchmark-worker
deployment/README.md
deployment/kubernetes/helm/benchmark/templates/benchmark-worker.yaml
deployment/kubernetes/helm/benchmark/templates/benchmark.yaml
docker/Dockerfile
docker/pom.xml
docker/run.sh

I recently encountered some environments where the container image may have its `PATH` modified by the container runtime. This was causing problems running the driver and worker scripts that just call `java` as if it's in the `PATH`.
Additionally, there were issues invoking the entrypoint commands. This ditches the format and approach from upstream. There's no need for a pod that does `tail /dev/null` when k8s can let you explicitly request a tty and `stdin` attached. This means instead of:
```
$ kubectl exec -it -n ns pod/omb-driver -- bash
```
You do:
```
$ kubectl attach -it -n ns omb-driver
```
This gets you connected to the running `bash` process in the pod without having to spawn an additional shell.
While here, this also tweaks how the base image and tag are configured for Maven, …

Refactor the Docker image and how the benchmark scripts are invoked

---

.gitattributes

A user that cloned the repo on Windows reported that the Docker image being built resulted in un-runnable benchmark scripts. Turns out that Git for Windows can default to substituting `\r\n` for `\n` for text files unless a `.gitattributes` file explicitly overrides this behavior.
This defines `.gitattributes` and explicitly lists the 3 scripts as text files that should not have line ending substitution performed. The only tradeoff is someone editing these files on Windows will need an editor that can detect and use the proper line endings, but this prevents the happy path (`clean`, `install`, `build:docker`) from resulting in a broken image.

Prevent git clones on Windows from adding `\r` to shell scripts

---

deployment/kubernetes/helm/benchmark/templates/benchmark-worker.yaml
deployment/kubernetes/helm/benchmark/templates/benchmark.yaml
deployment/kubernetes/helm/benchmark/templates/driverConfig.yaml
deployment/kubernetes/helm/benchmark/values.yaml

- Check for "name" key in caSecretRef, not caSecretRef itself.
- Refactor better defaults in values.yaml.
- Validate worker replica count defaults.
- Fix pvc name to use .Release.Name.

Fixes and improvements from AKS testing.

---

deployment/kubernetes/helm/benchmark/templates/benchmark-worker.yaml
deployment/kubernetes/helm/benchmark/templates/benchmark.yaml
deployment/kubernetes/helm/benchmark/values.yaml

We shouldn't schedule the OMB workers or driver on nodes that have Redpanda broker pods scheduled.
Ideally, we wouldn't schedule the driver on the same node as the workers.

Avoid scheduling OMB components on nodes running Redpanda

---

docker/pom.xml

Updates the `docker-maven-plugin` to allow building Docker images for both `linux/amd64` and `linux/arm64`. This means to build and push for both platforms, it's a simple:
```
$ mvn docker:push -pl docker -Ddocker.organization=<my-dockerhub-acct>
```
Building for a single platform is possible by overriding `docker.platforms`:
```
$ mvn docker:build -pl docker -Ddocker.platforms=linux/amd64
```

Enable multi-platform Docker builds (linux/amd64, linux/arm64)

---

deployment/kubernetes/helm/benchmark/templates/_helpers.tpl

My original logic was flawed and results in not being able to generate a `SASL_PLAINTEXT` setting required for some Apache Kafka environments.

Fix TLS-enabled check in security protocol builder template logic.

---

benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/CumulativeLatencies.java
benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/PeriodStats.java

This is a follow on to 95732ddd17b38509e7aacc0f06ab7e552cd10b9a.
This makes also the CumulativeLatencies histograms be auto-adjusting since they can fail in the same way. See the other commit for details.

Use more auto-adjusting histograms

---

benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/WorkerHandler.java
bin/benchmark
bin/benchmark-worker

The way worker nodes work in OMB is that there is a Worker facade
which hides wether there is a single LocalWorker or distributed workers
across multiple hosts. We collect all the statistics back to the
primary node (the one running bin/benchmark) and then log there, but
these log lines always reflect the aggregate statistics for all
workers.
When diagnosing performance issues it is useful to see the metrics for
individual workers as well, since correlated slowdowns imply something
different than uncorrelated ones (correlated slowdowns are highly
unlikely to be caused by a client/worker effect since they are on
independent hosts).
This change logs similar latency information to the primary node, on
each worker, at the same frequency as the primary node (specifically,
it logs when the …

Worker logging

---

benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java
benchmark-framework/src/main/java/io/openmessaging/benchmark/utils/distributor/KeyDistributorType.java

Currently we allow unknown properties in the workload file, so something like a typo will be silently accepted.
This occurs because we explicitly configure the jackson mapper to allow unknown properties (the default is not to allow them), which is likely because we re-use the same mapper object to deserialize the driver file, which does need to pass through arbitrary properties to the driver. However, the other mapper uses seem like they'd be better off with a strict mapper.
This changes splits the mappers: using a unknown-properties-allowed mapper only for the driver config file.

Fail on unknown properties

---

benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java

When running tests with a large number of producers per OMB client machine (>100), there's a noticeable startup delay. It turns out that, while futures were being used, they were only being advanced serially.
While here, improve some logging in this area.
For reference, starting a test with 960 producers can take ~5 minutes to perform the probing. Eventually one will hit a hardcoded http client timeout in OMB as the text executor/orchestrator times out waiting for the worker to reply to the HTTP request triggering the probe.

Parallelize producer probes in LocalWorker. Add logging.

---

benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java
benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/SwarmWorker.java

There's no reason to do this serially. Plus, it removes dependency on a Pulsar class in lieu of native Java features.

Send POSTs to workers in parallel

---

benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java

When a test starts up and "probes" a large number of producers in parallel, they currently all try writing to the same topic partition. This puts all the stress on a single Redpanda shard. Using a `null` key helps distribute this load across partitions and, consequently, across shards.

Probe topic partitions using a null key to distribute work.

---

driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/RedpandaBenchmarkDriver.java

While troubleshooting an issue with some OMB workers, it seems the driver instances were getting into a strange state where they were partially initialized. Consequently, the admin client reference was `null`, and starting a new test would trigger NPEs on all the workers.
This puts a little bit of safety around that area and makes sure we actually clean out state so a new test run can properly re-initialize things.

Prevent NPE when the `stop-all` call is issued to borked workers

---

driver-redpanda/README.md
driver-redpanda/deploy/certification/README.md
driver-redpanda/pom.xml
driver-redpanda/redpanda-ack-0.yaml
driver-redpanda/redpanda-ack-1-linger-1ms-eod-false.yaml
driver-redpanda/redpanda-ack-1.yaml
driver-redpanda/redpanda-ack-all-group-linger-10ms.yaml
driver-redpanda/redpanda-ack-all-group-linger-1ms.yaml
driver-redpanda/redpanda-ack-all-linger-1ms-eod-false.yaml
driver-redpanda/redpanda-ack-all-linger-1ms-eod-true.yaml
driver-redpanda/redpanda-ack-all-linger-1ms.yaml
driver-redpanda/redpanda-ack-all.yaml
driver-redpanda/redpanda-exactly-once.yaml
driver-redpanda/redpanda-group-all.yaml
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/Config.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/RedpandaBenchmarkConsumer.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/RedpandaBenchmarkDriver.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/RedpandaBenchmarkProducer.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/swarm/RedpandaBenchmarkConsumer.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/swarm/RedpandaBenchmarkDriver.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/swarm/RedpandaBenchmarkProducer.java
pom.xml

I grew tired of having to always add `-Dlicense.skip=true` to my args list. I can never remember if it's `skip.license`, etc. This makes `license-maven-plugin` happy.
- bumps license-maven-plugin to v4.3
- ignores the `driver-redpanda/deploy` assets
- tweaks all header files to use included Apache v2 header format
- updates README's in driver-redpanda

Update and tweak license headers to work with license-maven-plugin.

---

driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/swarm/RedpandaBenchmarkDriver.java

The "swarm" driver nukes the world, which is a horrible thing to do in a Redpanda Cloud instance. 
Skip topics that start with `"_"`.

Prevent Swarm driver from deleting internal topics

---

benchmark-framework/src/main/java/io/openmessaging/benchmark/Workload.java
benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/TopicsInfo.java

It is sometimes useful to run a test without consumers, e.g., to test the produce latency in isolation. OMB supports this: just set subcriptionsPerTopic to 0 (or consumers per subscription to 0, etc).
However, in zero consumer mode each benchmark is delayed for a minute while we wait for consumers to be "ready", which means that they have received the probe message we sent out. Since there are no consumers, this will never happen.
After this change we skip this check when there are no consumers.

Don't wait for consumers if there are none

---

driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/RedpandaBenchmarkDriver.java

Every worker will have initializeDriver called and there we implement the 'reset' functionality which deletes all existing topics created by OMB from prior runs. *All* producers do this more or less simultaneously because there currently no mechanism to single out one producer to do that work. So if you have 2 or more producers they are racing to delete the same topics.
We already catch the expected exception type which occurs when a deleter loses the race and just log, but it turns out that some Kafka implementations can also throw UnknownTopicIdException which is similar. So catch and log in that case too.

RedpandaDriver: fix (again) topic deletion race

---

driver-redpanda/pom.xml

driver-redpanda cannot use zstd compression because it fails to find the class. Adding this dependency explicitly ensures that we have a copy of the required classes for the Redpanda driver.

Fix that zstd is not linking properly for redpanda-driver

---

driver-redpanda/redpanda-ack-all-tx-2.yaml
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/RedpandaBenchmarkDriverBase.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/swarm/RedpandaBenchmarkDriver.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/tx/Config.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/tx/RedpandaBenchmarkDriver.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/tx/RedpandaBenchmarkProducer.java

Added a simple Redpanda driver that leverages transactions. The producer produces to the partitions using atomic produce. The transaction is committed every configurable number of messages. This way the user can control the overhead of transaction related request in standard open messaging benchmark.

Added very simple transactions benchmark

---

driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/RedpandaBenchmarkDriver.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/swarm/RedpandaBenchmarkDriver.java
driver-redpanda/src/main/java/io/openmessaging/benchmark/driver/redpanda/tx/RedpandaBenchmarkDriver.java

The standard driver was not actually setting all the consumer properties
because passing the properties to the constructor just sets the defaults
for `get` but doesn't actually set values to the keys.

driver-redpanda: Fix incorrect consumer property initialization

---

driver-redpanda/deploy/provision-redpanda-aws.tf

Added terraform code snippet to allow `ping` between ec2 instances.  This is required to validate n/w latency between instances while simulating stretch clusters in omb tests

Allow pings between ec2 instances

---

benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java

It is valid to run a benchmark with 0 producers, e.g., by setting `producersPerTopic: 0`. This works already in local mode, but in distributed mode you get an exception about the rate being NaN or Inf.
This is due to a divide-by-zero in the step that distributes the work among all the local workers.

fix zero-producer case

---

driver-redpanda/deploy/deploy.yaml

The syntax prevented the playbook from deploying.  This corrects that such that the repo can work as-is again.

Corrected syntax on Node Exporter install 

---

driver-redpanda/deploy/provision-redpanda-aws.tf
driver-redpanda/deploy/terraform.tfvars.example

If you're planning to benchmark against an existing private BYOC cluster, you'll probably want to peer the benchmark VPC to your BYOC VPC.   If you supply your vpc id & cidr in tfvars, terraform will peer the newly created benchmark VPC to your BYOC VPC. 
If you had been doing this manually, you had to first delete the peering and the routes before you could terraform destroy.
Supplying `null` for the peering variables to bypass the peering logic.

AWS peering
